Vagrant.configure("2") do |config|
	config.vm.boot_timeout = 400
	
	#enterprise vm
	config.vm.define "enterprise" do |master|
		master.vm.hostname = "enterprise.qac.local"
		master.vm.box = "chad-thompson/ubuntu-trusty64-gui"
		master.vm.network :public_network, :public_network => "wlan0", ip: "192.168.1.226"
		master.vm.provider :virtualbox do |masterVM|
			masterVM.gui = false
			masterVM.name = "enterprise"
			masterVM.memory = 4096
			masterVM.cpus = 2
		end
	end
	
	#agent mook vm
	config.vm.define "mook" do |agent|
		agent.vm.hostname = "mook.qac.local"
		agent.vm.box = "chad-thompson/ubuntu-trusty64-gui"
		agent.vm.network :public_network, :public_network => "wlan0", ip: "192.168.1.227"
		agent.vm.provision :shell, path: "agent_bootstrap.sh"
		agent.vm.provider :virtualbox do |agentVM|
			agentVM.gui = false
			agentVM.name = "mook"
			agentVM.memory = 4096
			agentVM.cpus = 2
		end
	end
end